"""Export service — generates Python scripts and Jupyter notebooks from pipelines.

Traverses the pipeline DAG in topological order, collects code snippets from each
node package's `code_snippet.py`, resolves variable names between connected nodes,
and produces either a standalone .py file or a .ipynb notebook.
"""

from __future__ import annotations

import importlib.util
import json
import textwrap
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.logging import get_logger
from models.pipeline import PipelineJSON
from services.dag_executor import DAGExecutor
from services.node_registry import NodeRegistry

logger = get_logger(__name__)

# Port type → variable prefix for readable generated code
_VAR_PREFIXES: dict[str, str] = {
    "dataframe_out": "df",
    "dataframe_in": "df",
    "split_data_out": "split",
    "split_data_in": "split",
    "model_out": "model",
    "model_in": "model",
    "metrics_out": "metrics",
    "plot_out": "fig",
}


class ExportService:
    """Generates standalone Python scripts and Jupyter notebooks from pipelines."""

    def __init__(self, registry: NodeRegistry) -> None:
        self.registry = registry
        self._snippet_cache: dict[str, Any] = {}

    # ── Public API ────────────────────────────────────────────────────────────

    def export_python(
        self,
        pipeline: PipelineJSON,
        pipeline_name: str = "Untitled Pipeline",
    ) -> str:
        """Return a complete .py script as a string."""
        order, node_map, edge_map = self._prepare(pipeline)
        var_map = self._build_variable_map(order, node_map, edge_map, pipeline)
        imports_set: list[str] = []
        code_blocks: list[str] = []

        for node_id in order:
            node = node_map[node_id]
            snippet_mod = self._load_snippet(node.type)
            if snippet_mod is None:
                code_blocks.append(f"# TODO: No code_snippet.py for {node.type}\n")
                continue

            input_vars = self._resolve_input_vars(node_id, edge_map, var_map)
            output_vars = var_map.get(node_id, {})

            imports, code = snippet_mod.get_snippet(
                params=dict(node.parameters),
                input_vars=input_vars,
                output_vars=output_vars,
                label=node.label,
            )

            for imp in imports:
                if imp not in imports_set:
                    imports_set.append(imp)

            code_blocks.append(code)

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        header = (
            f'# Generated by VRL ML Studio v1.0.0\n'
            f'# Pipeline: {pipeline_name}\n'
            f'# Generated: {now}\n'
            f'# ──────────────────────────────────────────────\n\n'
        )

        imports_block = "\n".join(imports_set) + "\n\n" if imports_set else ""

        steps = []
        for i, block in enumerate(code_blocks, 1):
            node = node_map[order[i - 1]]
            step_comment = f"# Step {i}: {node.label}\n"
            steps.append(step_comment + block)

        return header + imports_block + "\n".join(steps) + "\n"

    def export_notebook(
        self,
        pipeline: PipelineJSON,
        pipeline_name: str = "Untitled Pipeline",
    ) -> dict:
        """Return a .ipynb JSON structure (dict)."""
        order, node_map, edge_map = self._prepare(pipeline)
        var_map = self._build_variable_map(order, node_map, edge_map, pipeline)

        cells: list[dict] = []
        all_imports: list[str] = []
        step_cells: list[tuple[str, list[str], str]] = []  # (label, imports, code)

        for node_id in order:
            node = node_map[node_id]
            snippet_mod = self._load_snippet(node.type)
            if snippet_mod is None:
                step_cells.append((
                    node.label,
                    [],
                    f"# TODO: No code_snippet.py for {node.type}\n",
                ))
                continue

            input_vars = self._resolve_input_vars(node_id, edge_map, var_map)
            output_vars = var_map.get(node_id, {})

            imports, code = snippet_mod.get_snippet(
                params=dict(node.parameters),
                input_vars=input_vars,
                output_vars=output_vars,
                label=node.label,
            )

            for imp in imports:
                if imp not in all_imports:
                    all_imports.append(imp)

            step_cells.append((node.label, imports, code))

        # Cell 0: pip install
        requirements = self._derive_requirements(all_imports)
        if requirements:
            pip_source = f"# Install required packages\n!pip install -q {' '.join(requirements)}\n"
            cells.append(self._code_cell(pip_source))

        # Cell 1: imports
        if all_imports:
            cells.append(self._markdown_cell("## Imports"))
            cells.append(self._code_cell("\n".join(all_imports) + "\n"))

        # Subsequent cells: one markdown + one code per step
        for i, (label, _imports, code) in enumerate(step_cells, 1):
            cells.append(self._markdown_cell(f"## Step {i}: {label}"))
            cells.append(self._code_cell(code))

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        title_cell = self._markdown_cell(
            f"# {pipeline_name}\n\n"
            f"Generated by **VRL ML Studio** v1.0.0 — {now}"
        )
        cells.insert(0, title_cell)

        return {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {
                    "name": "python",
                    "version": "3.11.0",
                },
            },
            "cells": cells,
        }

    # ── Private helpers ───────────────────────────────────────────────────────

    def _prepare(self, pipeline: PipelineJSON):
        """Return (topological_order, node_map, edge_map)."""
        # Reuse DAGExecutor's topological sort
        from services.cache import CacheService

        dag = DAGExecutor(registry=self.registry, cache=CacheService())
        order = dag.topological_sort(pipeline.nodes, pipeline.edges)

        node_map = {n.id: n for n in pipeline.nodes}
        # Group edges by target node
        edge_map: dict[str, list] = defaultdict(list)
        for edge in pipeline.edges:
            edge_map[edge.target].append(edge)

        return order, node_map, edge_map

    def _build_variable_map(
        self,
        order: list[str],
        node_map: dict,
        edge_map: dict,
        pipeline: PipelineJSON,
    ) -> dict[str, dict[str, str]]:
        """Assign readable variable names to each node's output ports.

        Returns: { node_id: { port_id: variable_name } }
        """
        counters: dict[str, int] = defaultdict(int)
        var_map: dict[str, dict[str, str]] = {}

        for node_id in order:
            node = node_map[node_id]
            manifest = self.registry.get_manifest(node.type)
            outputs: dict[str, str] = {}

            if manifest is None:
                var_map[node_id] = outputs
                continue

            for port in manifest.get("outputs", []):
                port_id = port["id"]
                prefix = _VAR_PREFIXES.get(port_id, "var")
                counters[prefix] += 1
                # Make a clean suffix from the node label
                label_suffix = self._label_to_suffix(node.label)
                if counters[prefix] == 1 and label_suffix:
                    var_name = f"{prefix}_{label_suffix}"
                else:
                    var_name = f"{prefix}_{counters[prefix]}"
                outputs[port_id] = var_name

            var_map[node_id] = outputs

        return var_map

    def _resolve_input_vars(
        self,
        node_id: str,
        edge_map: dict[str, list],
        var_map: dict[str, dict[str, str]],
    ) -> dict[str, str]:
        """Map this node's input port IDs to the upstream variable names."""
        input_vars: dict[str, str] = {}
        for edge in edge_map.get(node_id, []):
            source_vars = var_map.get(edge.source, {})
            var_name = source_vars.get(edge.sourcePort, "UNKNOWN")
            input_vars[edge.targetPort] = var_name
        return input_vars

    def _load_snippet(self, node_type: str) -> Any | None:
        """Dynamically load a node package's code_snippet.py module."""
        if node_type in self._snippet_cache:
            return self._snippet_cache[node_type]

        # Resolve package directory
        pkg_dir = self.registry.get_package_dir(node_type)
        if pkg_dir is None:
            self._snippet_cache[node_type] = None
            return None

        snippet_path = Path(pkg_dir) / "code_snippet.py"
        if not snippet_path.exists():
            logger.warning("No code_snippet.py for node type %s", node_type)
            self._snippet_cache[node_type] = None
            return None

        spec = importlib.util.spec_from_file_location(
            f"code_snippet_{node_type}", str(snippet_path)
        )
        if spec is None or spec.loader is None:
            self._snippet_cache[node_type] = None
            return None

        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        self._snippet_cache[node_type] = module
        return module

    @staticmethod
    def _label_to_suffix(label: str) -> str:
        """Convert a node label like 'Titanic CSV' to 'titanic_csv'."""
        clean = "".join(c if c.isalnum() or c == " " else "" for c in label)
        parts = clean.lower().split()
        suffix = "_".join(parts[:3])  # keep it short
        return suffix if suffix else ""

    @staticmethod
    def _derive_requirements(imports: list[str]) -> list[str]:
        """Derive pip package names from import statements."""
        pkg_map: dict[str, str] = {
            "pandas": "pandas",
            "numpy": "numpy",
            "sklearn": "scikit-learn",
            "xgboost": "xgboost",
            "plotly": "plotly",
            "scipy": "scipy",
            "matplotlib": "matplotlib",
        }
        found: list[str] = []
        for line in imports:
            for module_name, pip_name in pkg_map.items():
                if module_name in line and pip_name not in found:
                    found.append(pip_name)
        return sorted(found)

    @staticmethod
    def _code_cell(source: str) -> dict:
        return {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": source.splitlines(keepends=True),
        }

    @staticmethod
    def _markdown_cell(source: str) -> dict:
        return {
            "cell_type": "markdown",
            "metadata": {},
            "source": source.splitlines(keepends=True),
        }
