"""Tests for the ExportService — Python script and Jupyter notebook generation."""

import json
import sys
from pathlib import Path

import pytest

# Ensure backend is on the path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from models.pipeline import PipelineEdge, PipelineJSON, PipelineNode, NodePosition
from services.export_service import ExportService
from services.node_registry import NodeRegistry


@pytest.fixture()
def registry():
    """A real registry with all builtin nodes loaded."""
    reg = NodeRegistry()
    reg.load_builtin_packages()
    return reg


@pytest.fixture()
def export_service(registry):
    return ExportService(registry=registry)


def _make_pipeline(nodes, edges):
    """Helper to create a PipelineJSON from dicts."""
    return PipelineJSON(
        version="1.0",
        nodes=[
            PipelineNode(
                id=n["id"],
                type=n["type"],
                label=n["label"],
                position=NodePosition(x=0, y=0),
                parameters=n.get("parameters", {}),
            )
            for n in nodes
        ],
        edges=[
            PipelineEdge(
                id=e["id"],
                source=e["source"],
                target=e["target"],
                sourcePort=e["sourcePort"],
                targetPort=e["targetPort"],
            )
            for e in edges
        ],
    )


# ── Classification pipeline ──────────────────────────────────────────────────


def _classification_pipeline():
    return _make_pipeline(
        nodes=[
            {
                "id": "n1",
                "type": "vrl.core.sample_dataset",
                "label": "Iris Dataset",
                "parameters": {"dataset": "iris"},
            },
            {
                "id": "n2",
                "type": "vrl.core.train_test_splitter",
                "label": "Splitter",
                "parameters": {"test_size": 0.2, "random_state": 42, "target_col": "target"},
            },
            {
                "id": "n3",
                "type": "vrl.core.random_forest_classifier",
                "label": "Random Forest",
                "parameters": {"n_estimators": 50, "random_state": 42},
            },
            {
                "id": "n4",
                "type": "vrl.core.classification_report",
                "label": "Report",
                "parameters": {"target_col": "target"},
            },
        ],
        edges=[
            {
                "id": "e1",
                "source": "n1",
                "target": "n2",
                "sourcePort": "dataframe_out",
                "targetPort": "dataframe_in",
            },
            {
                "id": "e2",
                "source": "n2",
                "target": "n3",
                "sourcePort": "split_data_out",
                "targetPort": "split_data_in",
            },
            {
                "id": "e3",
                "source": "n3",
                "target": "n4",
                "sourcePort": "model_out",
                "targetPort": "model_in",
            },
            {
                "id": "e4",
                "source": "n3",
                "target": "n4",
                "sourcePort": "dataframe_out",
                "targetPort": "dataframe_in",
            },
        ],
    )


class TestExportPython:
    def test_basic_export_produces_python_code(self, export_service):
        pipeline = _classification_pipeline()
        code = export_service.export_python(pipeline, "Iris Classification")

        assert "Generated by VRL ML Studio" in code
        assert "Pipeline: Iris Classification" in code
        assert "import" in code
        assert "RandomForestClassifier" in code
        assert "classification_report" in code

    def test_export_includes_steps(self, export_service):
        pipeline = _classification_pipeline()
        code = export_service.export_python(pipeline)

        assert "# Step 1:" in code
        assert "# Step 2:" in code
        assert "# Step 3:" in code
        assert "# Step 4:" in code

    def test_export_deduplicates_imports(self, export_service):
        pipeline = _classification_pipeline()
        code = export_service.export_python(pipeline)

        lines = code.split("\n")
        import_lines = [l for l in lines if l.startswith("import ") or l.startswith("from ")]
        # No duplicate imports
        assert len(import_lines) == len(set(import_lines))

    def test_single_node_export(self, export_service):
        pipeline = _make_pipeline(
            nodes=[{
                "id": "n1",
                "type": "vrl.core.sample_dataset",
                "label": "Iris",
                "parameters": {"dataset": "iris"},
            }],
            edges=[],
        )
        code = export_service.export_python(pipeline)
        assert "load_iris" in code
        assert "Step 1: Iris" in code


class TestExportNotebook:
    def test_basic_notebook_structure(self, export_service):
        pipeline = _classification_pipeline()
        nb = export_service.export_notebook(pipeline, "Iris Classification")

        assert nb["nbformat"] == 4
        assert "cells" in nb
        assert len(nb["cells"]) >= 5  # title + pip + imports + 4 steps

    def test_notebook_has_title_cell(self, export_service):
        pipeline = _classification_pipeline()
        nb = export_service.export_notebook(pipeline, "Iris Classification")

        title_cell = nb["cells"][0]
        assert title_cell["cell_type"] == "markdown"
        assert any("Iris Classification" in line for line in title_cell["source"])

    def test_notebook_has_pip_install(self, export_service):
        pipeline = _classification_pipeline()
        nb = export_service.export_notebook(pipeline, "Test")

        # Find the pip install cell
        pip_cells = [
            c for c in nb["cells"]
            if c["cell_type"] == "code" and any("pip install" in l for l in c["source"])
        ]
        assert len(pip_cells) == 1
        pip_src = "".join(pip_cells[0]["source"])
        assert "scikit-learn" in pip_src

    def test_notebook_has_markdown_step_headers(self, export_service):
        pipeline = _classification_pipeline()
        nb = export_service.export_notebook(pipeline)

        md_cells = [c for c in nb["cells"] if c["cell_type"] == "markdown"]
        step_cells = [
            c for c in md_cells
            if any("## Step" in line for line in c["source"])
        ]
        assert len(step_cells) == 4  # 4 nodes = 4 step headers

    def test_notebook_is_valid_json(self, export_service):
        pipeline = _classification_pipeline()
        nb = export_service.export_notebook(pipeline)

        # Should serialize to valid JSON
        json_str = json.dumps(nb)
        parsed = json.loads(json_str)
        assert parsed["nbformat"] == 4


class TestVariableNaming:
    def test_variables_are_readable(self, export_service):
        pipeline = _classification_pipeline()
        code = export_service.export_python(pipeline)

        # Should use prefix-based variable names, not raw node IDs
        assert "df_" in code or "split_" in code or "model_" in code

    def test_no_unknown_variables(self, export_service):
        pipeline = _classification_pipeline()
        code = export_service.export_python(pipeline)

        assert "UNKNOWN" not in code


class TestDeriveRequirements:
    def test_derives_sklearn(self):
        imports = ["from sklearn.ensemble import RandomForestClassifier"]
        reqs = ExportService._derive_requirements(imports)
        assert "scikit-learn" in reqs

    def test_derives_xgboost(self):
        imports = ["from xgboost import XGBClassifier"]
        reqs = ExportService._derive_requirements(imports)
        assert "xgboost" in reqs

    def test_derives_multiple(self):
        imports = [
            "import pandas as pd",
            "from sklearn.ensemble import RandomForestClassifier",
            "import plotly.express as px",
        ]
        reqs = ExportService._derive_requirements(imports)
        assert "pandas" in reqs
        assert "scikit-learn" in reqs
        assert "plotly" in reqs

    def test_deduplicates(self):
        imports = [
            "from sklearn.ensemble import RandomForestClassifier",
            "from sklearn.metrics import classification_report",
        ]
        reqs = ExportService._derive_requirements(imports)
        assert reqs.count("scikit-learn") == 1


class TestRegressionPipeline:
    def test_regression_export(self, export_service):
        pipeline = _make_pipeline(
            nodes=[
                {
                    "id": "n1",
                    "type": "vrl.core.sample_dataset",
                    "label": "Housing",
                    "parameters": {"dataset": "housing"},
                },
                {
                    "id": "n2",
                    "type": "vrl.core.train_test_splitter",
                    "label": "Split",
                    "parameters": {"test_size": 0.2, "random_state": 42, "target_col": "target"},
                },
                {
                    "id": "n3",
                    "type": "vrl.core.linear_regression",
                    "label": "LinReg",
                    "parameters": {},
                },
                {
                    "id": "n4",
                    "type": "vrl.core.regression_report",
                    "label": "Metrics",
                    "parameters": {"target_col": "target"},
                },
            ],
            edges=[
                {"id": "e1", "source": "n1", "target": "n2", "sourcePort": "dataframe_out", "targetPort": "dataframe_in"},
                {"id": "e2", "source": "n2", "target": "n3", "sourcePort": "split_data_out", "targetPort": "split_data_in"},
                {"id": "e3", "source": "n3", "target": "n4", "sourcePort": "model_out", "targetPort": "model_in"},
                {"id": "e4", "source": "n3", "target": "n4", "sourcePort": "dataframe_out", "targetPort": "dataframe_in"},
            ],
        )

        code = export_service.export_python(pipeline, "Housing Regression")
        assert "LinearRegression" in code
        assert "mean_absolute_error" in code


class TestClusteringPipeline:
    def test_clustering_export(self, export_service):
        pipeline = _make_pipeline(
            nodes=[
                {
                    "id": "n1",
                    "type": "vrl.core.sample_dataset",
                    "label": "Iris",
                    "parameters": {"dataset": "iris"},
                },
                {
                    "id": "n2",
                    "type": "vrl.core.kmeans",
                    "label": "KMeans",
                    "parameters": {"n_clusters": 3},
                },
            ],
            edges=[
                {"id": "e1", "source": "n1", "target": "n2", "sourcePort": "dataframe_out", "targetPort": "dataframe_in"},
            ],
        )

        code = export_service.export_python(pipeline, "Iris Clustering")
        assert "KMeans" in code
        assert "n_clusters=3" in code
